ALTER PROCEDURE [WEB].[VALE_RENDIR_LISTAR]
    @IND_TIPO_OPERACION CHAR(3) = 'GEN',
    @ID CHAR(16) = '', 
    @COD_EMPR CHAR(16) = '',
    @COD_CENTRO CHAR(16) = '',
    @USUARIO_AUTORIZA VARCHAR(50) = '',
    @USUARIO_APRUEBA VARCHAR(50) = '',
	@TIPO_MOTIVO VARCHAR(50)= '',
    @TXT_GLOSA VARCHAR(512) = '',
    @CAN_TOTAL_IMPORTE DECIMAL(18,2) = 0,
    @CAN_TOTAL_SALDO DECIMAL(18,2) = 0,
    @COD_USUARIO CHAR(16) = ''
AS
BEGIN TRY
    DECLARE @SQL VARCHAR(MAX);
    IF (@IND_TIPO_OPERACION = 'GEN')
    BEGIN
        SET @SQL = 'SELECT AU.ID, 
						   AU.FEC_USUARIO_CREA_AUD,
						   AU.COD_CENTRO, EMP.NOM_EMPR, 
						   EMP_TRAB.COD_EMPR AS COD_EMPR_CLIENTE,	
						   AU.COD_MONEDA,
                           US.NOM_TRABAJADOR AS USUARIO,
						   AU.USUARIO_AUTORIZA AS USUARIO_AUTORIZA_ID,
                           AU.TXT_NOM_AUTORIZA AS USUARIO_AUTORIZA, 
						   USUA.id AS USUARIO_AUTORIZADO, 
						   AU.USUARIO_APRUEBA AS USUARIO_APRUEBA_ID,
                           AU.TXT_NOM_APRUEBA AS USUARIO_APRUEBA,	   
						   USUAP.id AS USUARIO_APROBADO,
						   MOV.TXT_MOTIVO AS TIPO_MOTIVO,
                           AU.TXT_GLOSA,
                           AU.CAN_TOTAL_IMPORTE,
                           AU.CAN_TOTAL_SALDO,
						   AU.COD_CATEGORIA_ESTADO_VALE,
						   AU.TXT_CATEGORIA_ESTADO_VALE,
						   AU.TIPO_PAGO AS TIPO_PAGO,
						   AUT.TXT_TIPO_ESTADO AS ESTADO_OSIRIS,
						   AU.TXT_GLOSA_AUTORIZADO,
						   AU.TXT_GLOSA_RECHAZADO,
						   AU.TXT_GLOSA_APROBADO,
						   AU.COD_USUARIO_MODIF_AUD AS USUARIO_LOGUEADO
		
				        FROM WEB.VALE_RENDIR AS AU
						INNER JOIN STD.EMPRESA AS EMP ON EMP.COD_EMPR = AU.COD_EMPR
						INNER JOIN dbo.users AS USO ON USO.id = AU.COD_USUARIO_CREA_AUD
						INNER JOIN SGD.USUARIO AS USU ON USU.COD_TRABAJADOR = AU.USUARIO_AUTORIZA AND USU.COD_ESTADO = 1 
					    LEFT JOIN SGD.USUARIO AS USA ON USA.COD_TRABAJADOR = AU.USUARIO_APRUEBA AND USA.COD_ESTADO = 1
						INNER JOIN WEB.TIPO_MOTIVO AS MOV ON MOV.COD_MOTIVO = AU.TIPO_MOTIVO
						LEFT JOIN SGD.USUARIO AS US ON US.COD_TRABAJADOR = USO.usuarioosiris_id AND US.COD_ESTADO = 1 
						OUTER APPLY (
						SELECT TOP 1 *
							FROM WEB.VALE_PERSONAL_AUTORIZA TA
							WHERE TA.COD_AUTORIZA = USU.COD_TRABAJADOR) TA
						LEFT JOIN WEB.VALE_PERSONAL_APRUEBA AS AP ON AP.COD_APRUEBA = USA.COD_TRABAJADOR 
						LEFT JOIN STD.TRABAJADOR AS TRA ON TRA.COD_TRAB = US.COD_TRABAJADOR
						LEFT JOIN STD.EMPRESA AS EMP_TRAB ON EMP_TRAB.NRO_DOCUMENTO = TRA.NRO_DOCUMENTO AND EMP_TRAB.COD_ESTADO = 1
						LEFT JOIN dbo.users AS USUA ON USUA.usuarioosiris_id = AU.USUARIO_AUTORIZA
					    LEFT JOIN dbo.users AS USUAP ON USUAP.usuarioosiris_id = AU.USUARIO_APRUEBA
						LEFT JOIN TES.AUTORIZACION AS AUT ON AUT.COD_AUTORIZACION = AU.ID_OSIRIS
						WHERE AU.COD_ESTADO = 1';

      
        IF @ID <> ''
            SET @SQL = @SQL + ' AND AU.ID = ''' + @ID + '''';

        IF @COD_EMPR <> ''
            SET @SQL = @SQL + ' AND AU.COD_EMPR = ''' + @COD_EMPR + '''';

        IF @COD_CENTRO <> ''
            SET @SQL = @SQL + ' AND AU.COD_CENTRO = ''' + @COD_CENTRO + '''';

        IF @USUARIO_AUTORIZA <> ''
            SET @SQL = @SQL + ' AND AU.USUARIO_AUTORIZA = ''' + @USUARIO_AUTORIZA + '''';

		IF @TIPO_MOTIVO <> ''
            SET @SQL = @SQL + ' AND AU.TIPO_MOTIVO = ''' + @TIPO_MOTIVO + '''';

        IF @TXT_GLOSA <> ''
            SET @SQL = @SQL + ' AND AU.TXT_GLOSA = ''' + @TXT_GLOSA + '''';

        IF @CAN_TOTAL_IMPORTE <> 0
            SET @SQL = @SQL + ' AND AU.CAN_TOTAL_IMPORTE = ' + CAST(@CAN_TOTAL_IMPORTE AS VARCHAR(18));

        IF @CAN_TOTAL_SALDO <> 0
            SET @SQL = @SQL + ' AND AU.CAN_TOTAL_SALDO = ' + CAST(@CAN_TOTAL_SALDO AS VARCHAR(18));

        IF @COD_USUARIO <> ''
            SET @SQL = @SQL + ' AND AU.COD_USUARIO_CREA_AUD = ''' + @COD_USUARIO + '''';

       
        SET @SQL = @SQL + ' ORDER BY AU.ID DESC';
		print @SQL;
        EXEC(@SQL);
    END;

END TRY
BEGIN CATCH
    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;
    SELECT  @ErrorMessage = ERROR_MESSAGE(), 
            @ErrorSeverity = ERROR_SEVERITY(), 
            @ErrorState = ERROR_STATE();
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH
